# Generated by Django 2.0.6 on 2018-06-24 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default='1970-01-01 00:00:00')),
                ('game_outcome', models.IntegerField(default=0)),
                ('ranked_status', models.IntegerField(default=0)),
                ('players', models.CharField(default='NULL', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GameAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(default='NULL', max_length=200)),
                ('val', models.CharField(default='NULL', max_length=200)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayerRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='gameplayerrelationship',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player'),
        ),
    ]
