# Generated by Django 2.0.2 on 2018-05-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strife', '0003_auto_20180328_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='owner',
        ),
        migrations.AddField(
            model_name='game',
            name='game_outcome',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.CharField(default='NULL', max_length=1000),
        ),
        migrations.AddField(
            model_name='game',
            name='ranked_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='timestamp',
            field=models.DateTimeField(default='1970-01-01 00:00:00'),
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
