# Generated by Django 2.0.2 on 2018-02-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_gameids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='games',
            name='value',
        ),
        migrations.AddField(
            model_name='games',
            name='attr',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='games',
            name='val',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
