# Generated by Django 2.0.2 on 2018-02-15 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20180215_1306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameIDs',
            new_name='GamePlayerRelationship',
        ),
    ]
