# Generated by Django 2.0.2 on 2018-02-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20180216_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
            ],
        ),
    ]
