# Generated by Django 2.0.2 on 2018-02-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_winrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='winrate',
            name='win_rate',
            field=models.DecimalField(decimal_places=3, default=-1, max_digits=6),
        ),
    ]
