# Generated by Django 2.0.2 on 2018-03-13 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20180221_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('win_rate', models.DecimalField(decimal_places=3, default=-1, max_digits=6)),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Player')),
            ],
        ),
        migrations.DeleteModel(
            name='WinRate',
        ),
    ]
