# Generated by Django 2.0.2 on 2018-03-13 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20180313_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(default='NULL', max_length=200)),
                ('val', models.CharField(default='NULL', max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='gameplayerrelationship',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='gameplayerrelationship',
            old_name='player_name',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='playersummary',
            old_name='player_name',
            new_name='player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='attr',
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='val',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='gameattribute',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Game'),
        ),
    ]
